using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Notenmanager
{
    partial class MainView
    {
        public NotenmanagerData CurrentData;
        public string CurrentFilePath;
        public MainView()
        {
            InitializeComponent();
            CurrentFilePath = "Notenmanager.json";
            CurrentData = new NotenmanagerData();
            CurrentData.learningFields = new List<string>();
            CurrentData.subjects = new List<string>();
            CurrentData.exams = new List<Exam>();

            buttons["exit"].Clicked += OnExitClicked;
            buttons["addExam"].Clicked += OnExamAddClicked;
            buttons["load"].Clicked += OnLoadClicked;
            buttons["save"].Clicked += OnSaveClicked;

            buttons["listExams"].Clicked += OnExamListClicked;
            buttons["listSubjects"].Clicked += OnListSubjectsClicked;
            buttons["listLearningFields"].Clicked += OnListLearningFieldsClicked;

            // Export Button noch nicht implementiert, also visuell ausblenden
            buttons["export"].CanFocus = false;
            buttons["export"].ColorScheme = Program.GLOBAL_CS_ERROR;
        }

        private void ChangeState(string state)
        {
            switch (state)
            {
                case "loaded":
                    status.Text = "Datei geladen und aktuell";
                    status.ColorScheme = Program.GLOBAL_CS_FINE;
                    break;
                case "saved":
                    status.Text = "Datei gespeichert und aktuell";
                    status.ColorScheme = Program.GLOBAL_CS_FINE;
                    break;
                case "examAdded":
                    status.Text = "Neue Klausuren wurden erstellt, aber noch nicht abgespeichert!";
                    status.ColorScheme = Program.GLOBAL_CS_ERROR;
                    break;
                case "added":
                    status.Text = "Es wurden neue Elemente hinzugefügt, aber noch nicht abgespeichert!";
                    status.ColorScheme = Program.GLOBAL_CS_ERROR;
                    break;
            }
        }
        private void OnListSubjectsClicked()
        {
            string[] subjects = CurrentData.subjects.ToArray();
            string text = "";
            foreach(string subject in subjects)
            {
                text += subject + "\n";
            }

            MessageBox.Query("Alle Themen", text, "Okay");
        }

        private void OnListLearningFieldsClicked()
        {
            string[] learningFields = CurrentData.learningFields.ToArray();
            string text = "";

            foreach(string learningField in learningFields)
            {
                text += learningField + "\n";
            }

            MessageBox.Query("Alle Lernfelder", text, "Okay");
        }

        private void OnLoadClicked()
        {
            FileDialog d = new OpenDialog("Laden", "Wählen Sie eine Datei aus die der Notenmanager die Daten laden soll.");
            Application.Run(d);
            if(!d.Canceled)
            {
                FileHandler fh = new FileHandler(d.FilePath.ToString());
                NotenmanagerData? data = fh.Load();
           
                if (data != null)
                {
                    CurrentData = data;
                    currentPath.Text = d.FilePath.ToString();
                    lastChanged.Text = "Letzte Änderung: " + CurrentData.changeDate.ToString("dd.MM.yyyy - HH:mm");
                    ChangeState("loaded");
                    MessageBox.Query("Info", $"Die Datei:\n\"{d.FilePath}\"\nwurde geladen.", "Okay");
                }
            }
        }

        private void OnSaveClicked()
        {
            FileDialog d = new SaveDialog("Speichern", "Wählen Sie einen Speicherort aus, in dem der Notenmanager die Daten speichern soll.");
            d.FilePath = CurrentFilePath;
            Application.Run(d);
            if (!d.Canceled)
            {
                FileHandler fh = new FileHandler(CurrentFilePath);
                fh.Data = CurrentData;
                fh.Save();
                ChangeState("saved");
                MessageBox.Query("Info", $"Die Datei:\n\"{d.FilePath}\"\nwurde gespeichert", "Okay");
            }
        }
        private void OnExamAddClicked()
        {
            ExamFormularView view = new ExamFormularView(CurrentData.subjects.ToList(), CurrentData.learningFields.ToList());
            Application.Run(view);

            if(view.CurrentExam != null)
            {
                CurrentData.exams.Add(view.CurrentExam);
                ChangeState("examAdded");
            }

            if(view.NewSubject != null)
            {
                if(!CurrentData.subjects.Contains(view.NewSubject))
                {
                    CurrentData.subjects.Add(view.NewSubject);
                    ChangeState("added");
                }
            }

            if(view.NewLearningField != null)
            {
                if(!CurrentData.learningFields.Contains(view.NewLearningField))
                {
                    CurrentData.learningFields.Add(view.NewLearningField);
                    ChangeState("added");
                }
            }
        }

        private void OnExitClicked()
        {
            Application.RequestStop();
        }

        private void OnExamListClicked()
        {
            ExamsView examsView = new ExamsView(CurrentData.subjects, CurrentData.learningFields, CurrentData.exams);
            Application.Run(examsView);

            if(examsView.NewExamList != null)
            {
                this.CurrentData.exams = examsView.NewExamList;
                ChangeState("examAdded");
            }
        }
    }
}
