using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Notenmanager
{
    partial class MainView
    {
        public NotenmanagerData CurrentData;
        public string CurrentFilePath;
        public MainView()
        {
            InitializeComponent();
            CurrentFilePath = "Notenmanager.json";
            CurrentData = new NotenmanagerData();
            CurrentData.learningFields = new List<string>();
            CurrentData.subjects = new List<string>();

            buttons["exit"].Clicked += OnExitClicked;
            buttons["addExam"].Clicked += OnExamAddClicked;
            buttons["load"].Clicked += OnLoadClicked;
            buttons["save"].Clicked += OnSaveClicked;

            buttons["listSubjects"].Clicked += OnListSubjectsClicked;
            buttons["listLearningFields"].Clicked += OnListLearningFieldsClicked;

            // Export Button noch nicht implementiert, also visuell ausblenden
            buttons["export"].CanFocus = false;
            buttons["export"].ColorScheme = Program.GLOBAL_CS_ERROR;
        }

        private void OnListSubjectsClicked()
        {
            string[] subjects = CurrentData.subjects.ToArray();
            string text = "";
            foreach(string subject in subjects)
            {
                text += subject + "\n";
            }

            MessageBox.Query("Alle Themen", text);
        }

        private void OnListLearningFieldsClicked()
        {
            string[] learningFields = CurrentData.learningFields.ToArray();
            string text = "";

            foreach(string learningField in learningFields)
            {
                text += learningField + "\n";
            }

            MessageBox.Query("Alle Lernfelder", text);
        }

        private void OnLoadClicked()
        {
            FileDialog d = new OpenDialog("Laden", "Wählen Sie eine Datei aus die der Notenmanager die Daten laden soll.");
            Application.Run(d);
            if(!d.Canceled)
            {
                FileHandler fh = new FileHandler(d.FilePath.ToString());
                NotenmanagerData? couldLoad = fh.Load();
           
                if (couldLoad != null)
                {
                    CurrentData = couldLoad;
                    MessageBox.Query("Info", $"Die Datei: \"{d.FilePath}\" wurde geladen.");
                }
            }
        }

        private void OnSaveClicked()
        {
            FileDialog d = new SaveDialog("Speichern", "Wählen Sie einen Speicherort aus, in dem der Notenmanager die Daten speichern soll.");
            d.FilePath = CurrentFilePath;
            Application.Run(d);
            if (!d.Canceled)
            {
                FileHandler fh = new FileHandler(CurrentFilePath);
                fh.Data = CurrentData;
                fh.Save();
                MessageBox.Query("Info", $"Die Datei: \"{d.FilePath}\" wurde gespeichert");
            }
        }
        private void OnExamAddClicked()
        {
            ExamFormularView view = new ExamFormularView(CurrentData.subjects.ToList(), CurrentData.learningFields.ToList());
            Application.Run(view);

            if(view.CurrentExam != null)
            {
                CurrentData.exams.Add(view.CurrentExam);
            }

            if(view.NewSubject != null)
            {
                if(!CurrentData.subjects.Contains(view.NewSubject))
                {
                    CurrentData.subjects.Add(view.NewSubject);
                }
            }

            if(view.NewLearningField != null)
            {
                if(!CurrentData.learningFields.Contains(view.NewLearningField))
                {
                    CurrentData.learningFields.Add(view.NewLearningField);
                }
            }
        }

        private void OnExitClicked()
        {
            Application.RequestStop();
        }
    }
}
