using System;
using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Notenmanager
{
    partial class MainView : Terminal.Gui.Window
    {
        private Label title;
        private Dictionary<string, Button> buttons = new Dictionary<string, Button>();
        private string[] buttonNames =
        {
            "Daten laden",
            "Daten speichern",
            "Klausur hinzufügen",
            "Klausuren auflisten",
            "Thema hinzufügen",
            "Thema auflisten",
            "Lernfeld hinzufügen",
            "Lernfelder auflisten",
            "Exportieren",
            "Exit"
        };

        private string[] buttonIDs =
        {
            "load",
            "save",
            "addExam",
            "listExams",
            "addSubject",
            "listSubjects",
            "addLearningField",
            "listLearningFields",
            "export",
            "exit"
        };
        private void InitializeComponent()
        {
            title = new Label("Notenmanager Hauptmenü");

            int count = buttonIDs.Length;
            int offset = (count / 2) * -1;
            int i = 0;

            title.X = Pos.Center();
            title.Y = Pos.Center() + (offset - 2);
            title.ColorScheme = Program.GLOBAL_CS_TITLE;
            this.Add(title);
            
            foreach(string key in buttonIDs)
            {
                buttons[key] = new Button(buttonNames[i]);
                buttons[key].X = Pos.Center();
                buttons[key].Y = Pos.Center() + offset;
                this.Add(buttons[key]);
                offset++;
                i++;
            }

            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.ColorScheme = Program.GLOBAL_CS;
            this.Title = "Ctrl+Q drücken um das Programm zu beenden";
        }
    }
}
