using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Notenmanager
{
    public partial class MainView
    {
        public MainView()
        {
            InitializeComponent();
            buttons["exit"].Clicked += OnExitClicked;
            buttons["addExam"].Clicked += OnExamAddClicked;
            buttons["load"].Clicked += OnLoadClicked;
            buttons["save"].Clicked += OnSaveClicked;

            // Export Button noch nicht implementiert, also visuell ausblenden
            buttons["export"].CanFocus = false;
            buttons["export"].ColorScheme = Program.GLOBAL_CS_ERROR;
        }

        private void OnLoadClicked()
        {
            FileDialog d = new OpenDialog("Laden", "Wählen Sie eine Datei aus die der Notenmanager die Daten laden soll.");
            Application.Run(d);
            if(!d.Canceled)
            {
                // TODO Lade die Datei in das Programm.
                MessageBox.Query("Info", $"Die Datei: \"{d.FilePath}\" wurde ausgewählt.");
            }
        }

        private void OnSaveClicked()
        {
            FileDialog d = new SaveDialog("Speichern", "Wählen Sie einen Speicherort aus, in dem der Notenmanager die Daten speichern soll.");
            Application.Run(d);
            if (!d.Canceled)
            {
                // TODO Speichere die ausgewählte Datei vom Programm.
                MessageBox.Query("Info", $"Die Datei: \"{d.FilePath}\" wurde ausgewählt");
            }
        }
        private void OnExamAddClicked()
        {
            string[] lf =
            {
                "Lernfeld1",
                "Lernfeld2",
                "LernfeldX",
            };

            string[] s =
            {
               "Thema1",
               "Thema2",
               "Thema3",
               "ThemaX",
            };
            Application.Run(new ExamFormularView(new List<string>(s), new List<string>(lf)));
        }

        private void OnExitClicked()
        {
            Application.RequestStop();
        }
    }
}
